<?php if ($is_new): ?>
<h1><?php echo $this->translate('Galerie_add_title', 'galerie'); ?></h1>
<?php else: ?>
<h1><?php echo $this->translate('Galerie_edit_title', 'galerie'); ?></h1>
<?php endif; ?>

<?php
echo $this->form()->openTag($form);
echo $this->formRow($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('description'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag($form);
?>
