<h1><?php echo $this->translate('Galerie_index_title', 'galerie'); ?></h1>

<table id="galeries">
	<tr>
		<th>
			<strong><?php echo $this->translate('Galerie_index_table_name', 'galerie'); ?></strong>
			<em><?php echo $this->translate('Galerie_index_table_description', 'galerie'); ?></em>
		</th>
		<th>
			<?php echo $this->translate('Galerie_index_table_username', 'galerie'); ?>
		</th>
		<th>
			<?php echo $this->translate('Galerie_index_table_nb', 'galerie'); ?>
		</th>
	</tr>
	<?php if ($galeries->count() == 0): ?>
	<tr>
		<td colspan="4">
			<strong><?php echo $this->translate('Galerie_index_table_void', 'galerie'); ?></strong>
		</td>
	</tr>
	<?php else: ?>
	<?php foreach($galeries as $galerie): ?>
	<tr>
		<td>
			<strong><?php echo $this->escapeHtml($galerie->name); ?></strong>
			<em><?php echo $this->escapeHtml($galerie->description); ?></em>
		</td>
		<td>
			<?php echo $this->escapeHtml($galerie->username); ?>
		</td>
		<td>
			<?php echo $this->escapeHtml($galerie->nb); ?>
		</td>
	</tr>
	<?php endforeach; ?>
	<?php endif; ?>
</table>
