<h1><?php echo $this->translate('Galerie_index_title', 'galerie'); ?></h1>

<table id="galeries" class="sorted">
	<thead>
		<tr>
			<th>
				<strong><?php echo $this->translate('Galerie_index_table_name', 'galerie'); ?></strong>
			</th>
			<th>
				<em><?php echo $this->translate('Galerie_index_table_description', 'galerie'); ?></em>
			</th>
			<th>
				<?php echo $this->translate('Galerie_index_table_username', 'galerie'); ?>
			</th>
			<th>
				<?php echo $this->translate('Galerie_index_table_nb', 'galerie'); ?>
			</th>
			<th>
				<?php echo $this->translate('Galerie_index_table_actions', 'galerie'); ?>
			</th>
		</tr>
	</thead>
	<tbody>
	</tbody>
</table>
