<p>vue <em>back-office</em> d&rsquo;une <strong>galerie</strong>&nbsp;: view</p>

<h1>Galerie courante</h1>
<p>Nom&nbsp;: <?php echo $galerie->name; ?></p>
<p>Description&nbsp;: <?php echo $galerie->description; ?></p>
<p>Propriétaire&nbsp;: <?php echo $galerie->username; ?></p>
<p>Nombre de photographies&nbsp;: <?php echo $galerie->nb; ?></p>

<h1>Photos</h1>

<p>
<?php foreach($photos as $photo): ?>
<?php /*var_dump($photo);exit;*/ ?>
<img src="<?php echo $this->url('galerie/photo', array('idgallery'=>$photo->id_gallery, 'filename'=>$photo->filename, 'ext'=>$photo->extension)); ?>" height="50px" width="50px" />
<?php endforeach; ?>
</p>

<h1>Navigation</h1>
<h2>Accès direct aux autres galeries</h2>
<ul>
<?php foreach($pairs as $id => $name): ?>
<li><a href="<?php echo $this->url('galerie/photo', array('id'=>$id)); ?>"><?php echo $name; ?></a></li>
<?php endforeach; ?>
</ul>

